name: Deploy Web-Client
on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - ".github/workflows/webclient-deploy.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  web-client-deploy-dapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        shell: bash
        run: npm install

      - name: Install dfx
        uses: dfinity/setup-dfx@main
        with:
          dfx-version: "0.16.1"

      - name: Confirm successful installation
        run: dfx --version

      - name: Build webclient app
        run: npm run build

      - name: Setup env to deploy
        run: |
          touch actions_identity.pem
          echo "${{ secrets.FUEL_DAO_APP_ADMIN_AND_PROPOSAL_SUBMITTER_PRIVATE_KEY }}" > actions_identity.pem
          dfx identity import --storage-mode plaintext actions actions_identity.pem
          rm actions_identity.pem
          dfx identity use actions

      - name: Get Principal ID
        run: dfx identity get-principal

      - name: Canister Status
        run: dfx canister status --network ic --all

      - name: Canister Status of canister we need to upgrade
        run: dfx canister status 67erj-tiaaa-aaaam-acnxa-cai --network ic

      - name: List permission
        run: dfx canister --network ic call 67erj-tiaaa-aaaam-acnxa-cai list_permitted '(record {permission = variant {Commit}})'

      - name: Grant permission 
        run: dfx canister --network ic call 67erj-tiaaa-aaaam-acnxa-cai grant_permission '(record { to_principal = principal "pbgix-ewvzz-xoxul-trr77-xbet3-7zvs3-ga55x-ocakc-7wej2-uccjk-rae"; permission = variant { Commit } })'
        
      - name: Deploy built webclient app on IC
        run: dfx deploy webclient --network ic
